### PR TITLE
LS review comments

### PR DESCRIPTION
**Pull request by ev-br**
Если сложность с merge конфликтами, давайте знать, помогу.

### CODE REVIEW

**Comment by MoskalenkoRomanBorisovich** [comment]
Conflicting files
CSP2020/CSP2020.pdf
CSP2020/CSP2020.tex

**Comment by ev-br** [comment]
Ok, will update the PR

**Comment by MoskalenkoRomanBorisovich** [comment]
I barely changed these two files, so we can replace them entirely. How to do it?

**Comment by ev-br** [comment]
Green again, able to merge.

**Comment by ev-br** [comment]
With `git`, you can of course just replace the file in the work dir and commit. 

But it's better to do `$ git rebase upstream/master`, and resolve the commits manually. 
Something along the lines of `$ git status` shows "both modified", open in the editor and search for ">>>>>" symbols).
Then `$ git add <filename>`, and `$ git rebase --continue`.

BUT, if you do that, always make a 'save' branch! `$ git checkout -b saved`, then switch back and rebase.

**Pull request merged**
